repos:
- repo: local
  hooks:
    - id: make-black
      name: make-black
      entry: make black
      language: system
      types: [ python ]
      require_serial: true
    - id: make-unit-tests
      name: make-unit-tests
      entry: make unit-tests
      language: system
      types: [ python ]
      require_serial: true
    - id: make-prepare-for-testing
      name: make-prepare-for-testing
      entry: make prepare-for-testing
      language: system
      types: [ python ]
      require_serial: true
