.PHONY: install pre-build build

## @CI_actions Installs the checked out version of the code using uv
install:
	uv sync --dev

## @CI_actions Runs code quality checks
pre-build: unit-tests
	rm setup.py || echo "There was no setup.py"

## @CI_actions Builds the project into an sdist
build:
	uv build
