.PHONY: black pycodestyle importanize

## @Code_quality Runs black on the checked out code
black:
	uv run black servicecatalog_puppet

## @Code_quality Runs importanize on the checked out code
importanize:
	uv run importanize servicecatalog_puppet

## @Code_quality Runs pycodestyle on the the checked out code
pycodestyle:
	uv run pycodestyle --statistics -qq servicecatalog_puppet

pre-commit: importanize black unit-tests prepare-for-testing
