#  Copyright 2022 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0

EXECUTOR_ACCOUNT_ID = "SCT_EXECUTOR_ACCOUNT_ID"
CACHE_INVALIDATOR = "SCT_CACHE_INVALIDATOR"
EXECUTION_MODE = "SCT_EXECUTION_MODE"
PUPPET_ACCOUNT_ID = "SCT_PUPPET_ACCOUNT_ID"
NUM_WORKERS = "SCT_NUM_WORKERS"
SHOULD_DELETE_ROLLBACK_COMPLETE_STACKS = "SCT_SHOULD_DELETE_ROLLBACK_COMPLETE_STACKS"
SHOULD_USE_PRODUCT_PLANS = "SCT_SHOULD_USE_PRODUCT_PLANS"
INITIALISER_STACK_TAGS = "SCT_INITIALISER_STACK_TAGS"
HOME_REGION = "SCT_HOME_REGION"
REGIONS = "SCT_REGIONS"
SHOULD_USE_SNS = "SCT_SHOULD_USE_SNS"
SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE = "SCT_SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE"
SHOULD_FORWARD_FAILURES_TO_OPSCENTER = "SCT_SHOULD_FORWARD_FAILURES_TO_OPSCENTER"
