# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
schema;seq_tags:
  type: map
  mapping:
    Key:
      type: str
    Value:
      type: str

schema;map_params:
  type: map
  mapping:
    regex;(.+):
      type: map
      mapping:
        default:
          type: str
        macro:
          type: map
          mapping:
            method:
              type: str
              enum: ['get_accounts_for_path']
            args:
              type: str
        ssm:
          type: map
          mapping:
            name:
              type: str
            region:
              type: str


schema;map_account_id:
  type: map
  mapping:
    account_id:
      type: str
    name:
      type: str
    email:
      type: str
    default_region:
      type: str
    regions_enabled:
      type: seq
      sequence:
        - type: str
    tags:
      type: seq
      sequence:
        - type: str
    parameters:
      include: map_params
    exclude:
      type: map
      mapping:
        accounts:
          type: seq
          sequence:
            - type: str
        ous:
          type: seq
          sequence:
            - type: str


schema;map_deploy_to:
  type: map
  mapping:
    accounts:
      type: seq
      sequence:
        - type: map
          mapping:
            account_id:
              type: str
            regions:
              type: any
    tags:
      type: seq
      sequence:
        - type: map
          mapping:
            tag:
              type: str
            regions:
              type: any


schema;map_launches:
  type: map
  mapping:
    regex;(.+):
      type: map
      mapping:
        portfolio:
          type: str
        product:
          type: str
        version:
          type: str
        sharing_mode:
          type: str
        status:
          type: str
          enum: ['provisioned', 'terminated']
        depends_on:
          type: seq
          sequence:
            - type: str
        parameters:
          include: map_params
        deploy_to:
          include: map_deploy_to

schema;map_spoke_local_portfolios:
  type: map
  mapping:
    regex;(.+):
      type: map
      mapping:
        portfolio:
          type: str
        sharing_mode:
          type: str
        product_generation_method:
          type: str
          enum: ['import', 'copy']
        associations:
          type: seq
          sequence:
            - type: str
        constraints:
          type: map
          mapping:
            launch:
              type: seq
              sequence:
                - type: map
                  mapping:
                    products:
                      type: str
                    product:
                      type: str
                    roles:
                      type: seq
                      sequence:
                        - type: str
        depends_on:
          type: seq
          sequence:
            - type: str
        deploy_to:
          include: map_deploy_to

schema;map_account_ou:
  type: map
  mapping:
    ou:
      type: str
      pattern: \/|(\/.{1,250})+|ou-[a-z0-9]{4,32}-[a-z0-9]{4,32}
    name:
      type: str
    default_region:
      type: str
    regions_enabled:
      type: seq
      sequence:
        - type: str
    tags:
      type: seq
      sequence:
        - type: str
    parameters:
      include: map_params
    exclude:
      type: map
      mapping:
        accounts:
          type: seq
          sequence:
            - type: str
        ous:
          type: seq
          sequence:
            - type: str


type: map
func: ext_schema
mapping:
  schema:
    type: str
    enum: ['puppet-2019-04-01']
    required: yes
  parameters:
    include: map_params
  accounts:
    type: seq
    matching: "any"
    sequence:
      - include: map_account_id
      - include: map_account_ou
  spoke-local-portfolios:
    include: map_spoke_local_portfolios
  launches:
    include: map_launches

