# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Initialiser template used to bring up the install ServiceCatalog-Puppet
  {"version": "0.91.0", "framework": "servicecatalog-puppet", "role": "initialiser"}

Parameters:
  EnabledRegions:
    Type: String
    Description: |
      Space or comma seperated list of AWS Regions for which your puppet should operate in
  ShouldCollectCloudformationEvents:
    Type: String
    AllowedValues:
      - True
      - False
    Default: False
  ShouldForwardEventsToEventbridge:
    Type: String
    AllowedValues:
      - True
      - False
    Default: False
  ShouldForwardFailuresToOpscenter:
    Type: String
    AllowedValues:
      - True
      - False
    Default: True
  PuppetCodePipelineRolePermissionBoundary:
    Type: String
    Description: IAM Permission Boundary to apply to the PuppetCodePipelineRole
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"
  SourceRolePermissionsBoundary:
    Type: String
    Description: IAM Permission Boundary to apply to the SourceRole
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"
  PuppetGenerateRolePermissionBoundary:
    Type: String
    Description: IAM Permission Boundary to apply to the PuppetGenerateRole
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"
  PuppetDeployRolePermissionBoundary:
    Type: String
    Description: IAM Permission Boundary to apply to the PuppetDeployRole
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"
  PuppetProvisioningRolePermissionsBoundary:
    Type: String
    Description: IAM Permission Boundary to apply to the PuppetProvisioningRole
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"
  CloudFormationDeployRolePermissionsBoundary:
    Type: String
    Description: IAM Permission Boundary to apply to the CloudFormationDeployRole
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"
  PuppetRolePermissionBoundary:
    Type: String
    Description: IAM Permission Boundary to apply to the PuppetRole
    Default: "arn:aws:iam::aws:policy/AdministratorAccess"
  DeployEnvironmentComputeType:
    Type: String
    Description: The AWS CodeBuild Environment Compute Type
    Default: BUILD_GENERAL1_SMALL
  DeployNumWorkers:
    Type: Number
    Description: Number of workers that should be used when running a deploy
    Default: 10
  PuppetRoleName:
    Type: String
    Default: PuppetRole
  PuppetRolePath:
    Type: String
    Default: /servicecatalog-puppet/

Resources:
  InitialiserRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PuppetInitialiser
      Path: /servicecatalog-puppet/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess

  InitialiserProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: servicecatalog-product-puppet-initialiser
      Description: "Initialiser for the framework"
      ServiceRole: !GetAtt InitialiserRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
          - Name: ENABLED_REGIONS
            Type: PLAINTEXT
            Value: !Join [",", !Split [", ", !Ref EnabledRegions]]

          - Name: SHOULD_COLLECT_CLOUDFORMATION_EVENTS
            Type: PLAINTEXT
            Value: !Ref ShouldCollectCloudformationEvents

          - Name: SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE
            Type: PLAINTEXT
            Value: !Ref ShouldForwardEventsToEventbridge

          - Name: SHOULD_FORWARD_FAILURES_TO_OPSCENTER
            Type: PLAINTEXT
            Value: !Ref ShouldForwardFailuresToOpscenter

          - Name: PUPPET_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId

          - Name: PUPPET_CODE_PIPELINE_ROLE_PERMISSION_BOUNDARY
            Type: PLAINTEXT
            Value: !Ref PuppetCodePipelineRolePermissionBoundary

          - Name: SOURCE_ROLE_PERMISSIONS_BOUNDARY
            Type: PLAINTEXT
            Value: !Ref SourceRolePermissionsBoundary

          - Name: PUPPET_GENERATE_ROLE_PERMISSION_BOUNDARY
            Type: PLAINTEXT
            Value: !Ref PuppetGenerateRolePermissionBoundary

          - Name: PUPPET_DEPLOY_ROLE_PERMISSION_BOUNDARY
            Type: PLAINTEXT
            Value: !Ref PuppetDeployRolePermissionBoundary

          - Name: PUPPET_PROVISIONING_ROLE_PERMISSIONS_BOUNDARY
            Type: PLAINTEXT
            Value: !Ref PuppetProvisioningRolePermissionsBoundary

          - Name: CLOUD_FORMATION_DEPLOY_ROLE_PERMISSIONS_BOUNDARY
            Type: PLAINTEXT
            Value: !Ref CloudFormationDeployRolePermissionsBoundary

          - Name: PUPPET_ROLE_PERMISSION_BOUNDARY
            Type: PLAINTEXT
            Value: !Ref PuppetRolePermissionBoundary

          - Name: DEPLOY_ENVIRONMENT_COMPUTE_TYPE
            Type: PLAINTEXT
            Value: !Ref DeployEnvironmentComputeType

          - Name: DEPLOY_NUM_WORKERS
            Type: PLAINTEXT
            Value: !Ref DeployNumWorkers

          - Name: PARTITION
            Type: PLAINTEXT
            Value: !Ref AWS::Partition
          - Name: PUPPET_ROLE_NAME
            Type: PLAINTEXT
            Value: !Ref PuppetRoleName
          - Name: PUPPET_ROLE_PATH
            Type: PLAINTEXT
            Value: !Ref PuppetRolePath

      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                python: 3.7
              commands:
                - pip install aws-service-catalog-puppet --upgrade
                - servicecatalog-puppet --info set-regions ${ENABLED_REGIONS}
                - servicecatalog-puppet set-config-value should_collect_cloudformation_events ${SHOULD_COLLECT_CLOUDFORMATION_EVENTS}
                - servicecatalog-puppet set-config-value should_forward_events_to_eventbridge ${SHOULD_FORWARD_EVENTS_TO_EVENTBRIDGE}
                - servicecatalog-puppet set-config-value should_forward_failures_to_opscenter ${SHOULD_FORWARD_FAILURES_TO_OPSCENTER}
                - servicecatalog-puppet bootstrap-spoke ${PUPPET_ACCOUNT_ID} --permission-boundary ${PUPPET_ROLE_PERMISSION_BOUNDARY} --puppet-role-name ${PUPPET_ROLE_NAME} --puppet-role-path ${PUPPET_ROLE_PATH}
            build:
              commands:
                - servicecatalog-puppet --info bootstrap --puppet-code-pipeline-role-permission-boundary ${PUPPET_CODE_PIPELINE_ROLE_PERMISSION_BOUNDARY} --source-role-permissions-boundary ${SOURCE_ROLE_PERMISSIONS_BOUNDARY} --puppet-generate-role-permission-boundary ${PUPPET_GENERATE_ROLE_PERMISSION_BOUNDARY} --puppet-deploy-role-permission-boundary ${PUPPET_DEPLOY_ROLE_PERMISSION_BOUNDARY} --puppet-provisioning-role-permissions-boundary ${PUPPET_PROVISIONING_ROLE_PERMISSIONS_BOUNDARY} --cloud-formation-deploy-role-permissions-boundary ${CLOUD_FORMATION_DEPLOY_ROLE_PERMISSIONS_BOUNDARY} --deploy_num_workers ${DEPLOY_NUM_WORKERS} --deploy_environment_compute_type ${DEPLOY_ENVIRONMENT_COMPUTE_TYPE} --puppet-role-name ${PUPPET_ROLE_NAME} --puppet-role-path ${PUPPET_ROLE_PATH}

      TimeoutInMinutes: 60

  StartInstallRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StartPuppetInstallRole
      Path: /servicecatalog-puppet/
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSCodeBuildDeveloperAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  StartInstallLambda:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt StartInstallRole.Arn
      Handler: "index.handler"
      Description: Lambda for starting Puppet CodeBuild Job
      Runtime: python3.7
      Timeout: 900
      Code:
        ZipFile: |
          import boto3
          import json
          import logging
          import time
          from urllib.request import Request, urlopen

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def handler(event, context):
              request_type = event['RequestType']
              codebuild_projectname = event.get('ResourceProperties').get('ProjectName')

              try:
                  logger.info(request_type)
                  if request_type in ['Create', 'Update']:
                      codebuild_client = boto3.client('codebuild')
                      logger.info("Starting CodeBuild Job: {}".format(codebuild_projectname))
                      codebuild_response = codebuild_client.start_build(
                          projectName = codebuild_projectname
                      )
                      build_id = codebuild_response.get('build').get('id')
                      build_status = 'IN_PROGRESS'
                      while build_status == 'IN_PROGRESS':
                          time.sleep(5)
                          build = codebuild_client.batch_get_builds(ids=[build_id]).get('builds')[0]
                          build_status = build.get('buildStatus')
                      if build_status != 'SUCCEEDED':
                          raise Exception(f"Build did not SUCCEED. Status: {build_status}")
                      send_response(event, context, "SUCCESS",
                                    {"Message": "Updated"})

                  elif request_type == 'Delete':
                      send_response(event, context, "SUCCESS",
                                    {"Message": "Deleted"})

                  else:
                      send_response(event, context, "FAILED",
                                    {"Message": "Unexpected"})

              except Exception as ex:
                  logger.error(ex)
                  send_response(event, context,"FAILED",
                                    {"Message": "Exception"})

          def send_response(e, c, rs, rd):
              r = json.dumps({
                  "Status": rs,
                  "Reason": "CloudWatch Log Stream: " + c.log_stream_name,
                  "PhysicalResourceId": c.log_stream_name,
                  "StackId": e['StackId'],
                  "RequestId": e['RequestId'],
                  "LogicalResourceId": e['LogicalResourceId'],
                  "Data": rd
              })
              d = str.encode(r)
              h = {
                  'content-type': '',
                  'content-length': str(len(d))
              }
              req = Request(e['ResponseURL'], data=d, method='PUT', headers=h)
              r = urlopen(req)
              logger.info("Status message: {} {}".format(r.msg, r.getcode()))

  StartInstall:
    Type: Custom::CustomResource
    DependsOn: InitialiserProject
    Properties:
      ServiceToken: !GetAtt StartInstallLambda.Arn
      ProjectName: !Ref InitialiserProject

Outputs:
  ServiceCatalogPuppetRepoConsoleURL:
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/codesuite/codecommit/repositories/ServiceCatalogPuppet/browse"
  ServiceCatalogPuppetRepoCloneURLSSH:
    Value: !Sub "ssh://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/ServiceCatalogPuppet"
  ServiceCatalogPuppetRepoCloneURLHTTPS:
    Value: !Sub "https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/ServiceCatalogPuppet"
