# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Bootstrap template used to bring up the main ServiceCatalog-Puppet AWS CodePipeline with dependencies
  {"version": "{{ VERSION }}", "framework": "servicecatalog-puppet", "role": "bootstrap-master"}

Parameters:
  Version:
    Type: String
    Default: "{{ VERSION }}"
  OrgIamRoleArn:
    Type: String
    Default: "None"
  WithManualApprovals:
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'

Conditions:
  ShouldUseOrgs: !Not [!Equals [!Ref OrgIamRoleArn, None]]
  HasManualApprovals: !Equals [!Ref WithManualApprovals, 'Yes']

Resources:
  ManualApprovalsParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /servicecatalog-puppet/manual-approvals
      Type: String
      Value: !Ref WithManualApprovals
      Tags:
        "ServiceCatalogPuppet:Actor": "Framework"

  Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: service-catalog-puppet-version
      Type: String
      Value: !Ref Version
      Tags:
        "ServiceCatalogPuppet:Actor": "Framework"

  ShareAcceptFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: ShareAcceptFunctionRole
      Path: /servicecatalog-puppet/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ServiceCatalogActions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: arn:aws:iam::*:role/servicecatalog-puppet/PuppetRole

  ProvisioningRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PuppetProvisioningRole
      Path: /servicecatalog-puppet/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Principal:
              AWS: !Sub "${AWS::AccountId}"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  CloudFormationDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudFormationDeployRole
      Path: /servicecatalog-puppet/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Principal:
              AWS: !Sub "${AWS::AccountId}"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PuppetCodePipelineRole
      Path: /servicecatalog-puppet/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"

  SourceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PuppetSourceRole
      Path: /servicecatalog-puppet/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  CodeRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryDescription: Repo to store the servicecatalog puppet solution
      RepositoryName: ServiceCatalogPuppet

  DryRunNotificationTopic:
    Type: AWS::SNS::Topic
    Condition: HasManualApprovals
    Properties:
      DisplayName: service-catalog-puppet-dry-run-approvals
      TopicName: service-catalog-puppet-dry-run-approvals

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      Name: !Sub "${AWS::StackName}-pipeline"
      ArtifactStores:
        {% for region in ALL_REGIONS %}
        - Region: {{ region }}
          ArtifactStore:
            Type: S3
            Location: !Sub "sc-puppet-pipeline-artifacts-${AWS::AccountId}-{{ region }}"
        {% endfor %}
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: CodeCommit
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: !GetAtt CodeRepo.Name
                BranchName: master
              OutputArtifacts:
                - Name: Source
              RunOrder: 1
              RoleArn: !GetAtt SourceRole.Arn
        - Name: Generate
          Actions:
            - Name: GenerateShares
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref GenerateSharesProject
              RunOrder: 1
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: GenerateShares
        - Name: Deploy
          Actions:
            - !If
              - HasManualApprovals
              - Name: DryRun
                ActionTypeId:
                  Category: Build
                  Owner: AWS
                  Version: 1
                  Provider: CodeBuild
                Configuration:
                  ProjectName: !Ref DryRunProject
                  PrimarySource: GenerateShares
                RunOrder: 1
                InputArtifacts:
                  - Name: GenerateShares
                OutputArtifacts:
                  - Name: DryRunProject
              - !Ref AWS::NoValue
            - !If
              - HasManualApprovals
              - Name: DryRunApproval
                ActionTypeId:
                  Category: Approval
                  Owner: AWS
                  Version: 1
                  Provider: Manual
                Configuration:
                  NotificationArn: !Ref DryRunNotificationTopic
                  CustomData: Approve when you are happy with the dry run.
                RunOrder: 2
              - !Ref AWS::NoValue
            - Name: Deploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref DeployProject
                PrimarySource: GenerateShares
              RunOrder: !If [HasManualApprovals, 3, 1]
              InputArtifacts:
                - Name: GenerateShares
              OutputArtifacts:
                - Name: DeployProject

  GenerateRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PuppetGenerateRole
      Path: /servicecatalog-puppet/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - !If
          - ShouldUseOrgs
          - PolicyName: Org
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - sts:AssumeRole
                  Resource: !Ref OrgIamRoleArn
          - !Ref AWS::NoValue

  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PuppetDeployRole
      Path: /servicecatalog-puppet/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess


  GenerateSharesProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: servicecatalog-puppet-generate
      Description: "builds out the products to be deployed"
      ServiceRole: !GetAtt GenerateRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
          {% if 'http' in VERSION %}
                - pip install {{ VERSION }}
          {% else %}
                - pip install aws-service-catalog-puppet=={{ VERSION }}
          {% endif %}
            build:
              commands:
                - servicecatalog-puppet --info expand manifest.yaml
                - servicecatalog-puppet --info generate-shares manifest-expanded.yaml
          artifacts:
            files:
              - manifest-expanded.yaml
              - data/*/*/*/*.json
              - shares/*/*/*.json
              - topic/*/*/*.json
            name: GenerateShares
      TimeoutInMinutes: 30
      Tags:
        - Key: "ServiceCatalogPuppet:Actor"
          Value: "Framework"

  DeployProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: servicecatalog-puppet-deploy
      Description: "deploys out the products to be deployed"
      ServiceRole: !GetAtt DeployRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
          {% if 'http' in VERSION %}
                - pip install {{ VERSION }}
          {% else %}
                - pip install aws-service-catalog-puppet=={{ VERSION }}
          {% endif %}
            build:
              commands:
                - servicecatalog-puppet --info deploy manifest-expanded.yaml
          artifacts:
            files:
              - results/*/*
              - output/*/*
            name: DeployProject

      TimeoutInMinutes: 60
      Tags:
        - Key: "ServiceCatalogPuppet:Actor"
          Value: "Framework"

  DryRunProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: servicecatalog-puppet-dryrun
      Description: "dry run of the puppet run"
      ServiceRole: !GetAtt DeployRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
          {% if 'http' in VERSION %}
                - pip install {{ VERSION }}
          {% else %}
                - pip install aws-service-catalog-puppet=={{ VERSION }}
          {% endif %}
            build:
              commands:
                - servicecatalog-puppet --info dry-run manifest-expanded.yaml
          artifacts:
            files:
              - results/*/*
              - output/*/*
            name: DryRunProject

      TimeoutInMinutes: 60
      Tags:
        - Key: "ServiceCatalogPuppet:Actor"
          Value: "Framework"


  SingleAccountRunProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: servicecatalog-puppet-single-account-run
      Description: "Runs puppet for a single account - SINGLE_ACCOUNT_ID"
      ServiceRole: !GetAtt GenerateRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1
        EnvironmentVariables:
          - Name: SINGLE_ACCOUNT_ID
            Type: PLAINTEXT
            Value: CHANGE_ME
          - Name: GIT_REPO
            Type: PLAINTEXT
            Value: !GetAtt CodeRepo.CloneUrlHttp
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
          {% if 'http' in VERSION %}
                - pip install {{ VERSION }}
          {% else %}
                - pip install aws-service-catalog-puppet=={{ VERSION }}
          {% endif %}
            build:
              commands:
                - aws codepipeline start-pipeline-execution  --name servicecatalog-puppet-pipeline
      TimeoutInMinutes: 30
      Tags:
        - Key: "ServiceCatalogPuppet:Actor"
          Value: "Framework"

  CloudFormationEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: servicecatalog-puppet-cloudformation-events
      Tags:
        - Key: "ServiceCatalogPuppet:Actor"
          Value: "Framework"

  CloudFormationEventsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: AllowSNS
        Version: '2012-10-17'
        Statement:
          - Sid: allow-send-message
            Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource: "*"
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub "arn:aws:sns:*:${AWS::AccountId}:servicecatalog-puppet-cloudformation-regional-events"
      Queues:
        - !Ref CloudFormationEventsQueue


Outputs:
  CloudFormationEventsQueueArn:
    Value: !GetAtt CloudFormationEventsQueue.Arn
  Version:
    Value: !GetAtt Param.Value
  ManualApprovalsParam:
    Value: !GetAtt ManualApprovalsParam.Value
