# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Version:
    Type: String
    Default: "{{ VERSION }}"
  DefaultRegionValue:
    Type: String

Resources:

  DefaultRegionParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /servicecatalog-puppet/home-region
      Type: String
      Value: !Ref DefaultRegionValue

  Param:
    Type: AWS::SSM::Parameter
    Properties:
      Name: service-catalog-puppet-regional-version
      Type: String
      Value: !Ref Version

  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "sc-puppet-pipeline-artifacts-${AWS::AccountId}-${AWS::Region}"
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 90
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled

  RegionalProductTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: servicecatalog-puppet-cloudformation-regional-events
      TopicName: servicecatalog-puppet-cloudformation-regional-events
      Subscription:
        - Endpoint: !Sub "arn:aws:sqs:${DefaultRegionValue}:${AWS::AccountId}:servicecatalog-puppet-cloudformation-events"
          Protocol: "sqs"

Outputs:
  Version:
    Value: !GetAtt Param.Value

  RegionalProductTopic:
    Value: !Ref RegionalProductTopic
