AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Account Vending Machine: this template uses a AWS Lambda backed custom resource to create an AWS Account.

Parameters:
  Email:
    Type: String
    Description: The email address to use for the account that is to be created
  AccountName:
    Type: String
    Description: The name to use for the account that is to be created
  OrganizationAccountAccessRole:
    Type: String
    Default: OrganizationAccountAccessRole
    Description: The name of the role to be created in the account that allows Organizations access
  IamUserAccessToBilling:
    Type: String
    Default: "ALLOW"
    AllowedValues: ['ALLOW', 'DENY']
  TargetOU:
    Type: String
    Default: None
    Description: OU/path where the created account should be moved to once creation is completed - None means no move
  AccountVendingMachineLambda:
    Type: String
    Default: account-vending-machine-lambda

Resources:
  Account:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref AccountVendingMachineLambda
      Email: !Ref Email
      AccountName: !Ref AccountName
      OrganizationAccountAccessRole: !Ref OrganizationAccountAccessRole
      IamUserAccessToBilling: !Ref IamUserAccessToBilling
      TargetOU: !Ref TargetOU

Outputs:
  AccountId:
    Value: !GetAtt Account.account_id