name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.7'
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install
      run: make install
    - name: run tests
      run: make unit-tests
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1

